/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.SwingConstants;
/**
 *
 * @author death
 */
public class AdminForm extends javax.swing.JFrame {

    /**
     * Creates new form AdminForm
     */
    public AdminForm(int userId) {
        
        setTitle("Mana Movie Rental System");
        
        initComponents();
        
        // Customer Button
        ImageIcon iconCustomers = new ImageIcon(getClass().getResource("/images/icon_Users.jpg"));
        Image scaledCustomers = iconCustomers.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH); 
        btnCustomers.setIcon(new ImageIcon(scaledCustomers)); 
        btnCustomers.setHorizontalTextPosition(SwingConstants.CENTER);
        btnCustomers.setVerticalTextPosition(SwingConstants.BOTTOM);
        
        // Movies Button
        ImageIcon iconMovies = new ImageIcon(getClass().getResource("/images/icon_Film.jpg"));
        Image scaledMovies = iconMovies.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH); 
        btnMovies.setIcon(new ImageIcon(scaledMovies)); 
        btnMovies.setHorizontalTextPosition(SwingConstants.CENTER);
        btnMovies.setVerticalTextPosition(SwingConstants.BOTTOM);
        
        // Rental Button
        ImageIcon iconRentals = new ImageIcon(getClass().getResource("/images/icon_Popcorn.jpeg"));
        Image scaledRentals = iconRentals.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH); 
        btnRentals.setIcon(new ImageIcon(scaledRentals)); 
        btnRentals.setHorizontalTextPosition(SwingConstants.CENTER);
        btnRentals.setVerticalTextPosition(SwingConstants.BOTTOM);
        
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        btnCustomers = new javax.swing.JButton();
        btnMovies = new javax.swing.JButton();
        btnRentals = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setText("Admin Dashboard");

        btnCustomers.setText("Customers");
        btnCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomersActionPerformed(evt);
            }
        });

        btnMovies.setText("Movies");
        btnMovies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoviesActionPerformed(evt);
            }
        });

        btnRentals.setText("Rentals");
        btnRentals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRentalsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(btnCustomers)
                        .addGap(64, 64, 64)
                        .addComponent(btnMovies)
                        .addGap(60, 60, 60)
                        .addComponent(btnRentals)))
                .addContainerGap(268, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel5)
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCustomers)
                    .addComponent(btnMovies)
                    .addComponent(btnRentals))
                .addContainerGap(268, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // START - Customers Button
    private void btnCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomersActionPerformed
        // TODO add your handling code here:
        
        new CustomerManagementForm().setVisible(true);
        
    }//GEN-LAST:event_btnCustomersActionPerformed
    // END - Customers Button

    // START - Movies Button
    private void btnMoviesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoviesActionPerformed
        // TODO add your handling code here:
        
        new MovieManagementForm().setVisible(true);

    }//GEN-LAST:event_btnMoviesActionPerformed
    // END - Movies Button

    // START - Rentals Button
    private void btnRentalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRentalsActionPerformed
        // TODO add your handling code here:
 
        new RentalManagementForm().setVisible(true);
        
    }//GEN-LAST:event_btnRentalsActionPerformed
    // END - Rentals Button

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminForm(1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCustomers;
    private javax.swing.JButton btnMovies;
    private javax.swing.JButton btnRentals;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
