
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author death
 */
public class RentalManagementForm extends javax.swing.JFrame {

    /**
     * Creates new form RentalManagementForm
     */
    public RentalManagementForm() {
        
        setTitle("Mana Movie Rental System");
        
        initComponents();
        
        loadRentals();
    }
    
    
    // START - LoadRentals
    public void loadRentals() {
        
        try (Connection conn = DBConnection.connect()) {
            
            
            //ADDED to FROM Rentals 
            // ADDED WHERE returned = FALSE 
            String sql = "SELECT Movies.id AS movie_id, Movies.title AS movie_title, " +
                        "Rentals.format, " +
                        "Users.id AS user_id, CONCAT(Users.first_name, ' ', Users.last_name) AS customer_name, " +
                        "Rentals.rent_date, Rentals.return_date " +
                        "FROM Rentals " +
                        "JOIN Users ON Rentals.customer_id = Users.id " +
                        "JOIN Movies ON Rentals.movie_id = Movies.id " + 
                        "WHERE Rentals.status != 'Returned' ";

            PreparedStatement stmt = conn.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();

            DefaultTableModel model = new DefaultTableModel(
                new String[] { "Movie ID", "Movie Name", "Format", "Customer ID", "Customer Name", "Rented Date", "Return Date", "Status" }, 0
            );

            while (rs.next()) {
                
                String returnDateStr = rs.getString("return_date"); 
                String status = "Normal"; 
                
                if (returnDateStr != null) {
                    
                    java.sql.Date returnDate = java.sql.Date.valueOf(returnDateStr); 
                    java.sql.Date today = new java.sql.Date(System.currentTimeMillis()); 
                    
                    
                    
                    if (today.after(returnDate)){
                        
                        status = "Past Due";
                        
                    }
                    
                }
                
                model.addRow(new Object[] {
                    rs.getInt("movie_id"),
                    rs.getString("movie_title"),
                    rs.getString("format"),
                    rs.getInt("user_id"),
                    rs.getString("customer_name"),
                    rs.getString("rent_date"),
                    rs.getString("return_date"), 
                    status
                        
                });
            }

            tableRentals.setModel(model);
            
        } catch (Exception e) {
            
            e.printStackTrace(); 
            JOptionPane.showMessageDialog(this, "Error loading rentals.");
            
        }
        
    }
    // END - LoadRentals

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnReturnMovie = new javax.swing.JButton();
        btnAddRental = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableRentals = new javax.swing.JTable();
        btnReservations = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Rental Management Form");

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnReturnMovie.setText("Return Rental");
        btnReturnMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnMovieActionPerformed(evt);
            }
        });

        btnAddRental.setText("Add Rental");
        btnAddRental.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRentalActionPerformed(evt);
            }
        });

        tableRentals.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableRentals);

        btnReservations.setText("Reservations");
        btnReservations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservationsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(323, 323, 323)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 754, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnReturnMovie)
                        .addGap(32, 32, 32)
                        .addComponent(btnAddRental)
                        .addGap(31, 31, 31)
                        .addComponent(btnReservations)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBack)))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBack)
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnReturnMovie)
                            .addComponent(btnAddRental)
                            .addComponent(btnReservations))
                        .addContainerGap(29, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddRentalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRentalActionPerformed
        // TODO add your handling code here:
        
        AddRentalPromptForm promptForm = new AddRentalPromptForm(this); 
        promptForm.setVisible(true);
        
    }//GEN-LAST:event_btnAddRentalActionPerformed

    private void btnReturnMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnMovieActionPerformed
        // TODO add your handling code here:
        
        ReturnRentalPromptForm promptForm = new ReturnRentalPromptForm(this); 
        promptForm.setVisible(true);
        
        
    }//GEN-LAST:event_btnReturnMovieActionPerformed

    private void btnReservationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservationsActionPerformed
        // TODO add your handling code here:
        
        ReservationPromptForm promptForm = new ReservationPromptForm(this);
        promptForm.setVisible(true);
        
    }//GEN-LAST:event_btnReservationsActionPerformed

    
   // END - Customers Section

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RentalManagementForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RentalManagementForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RentalManagementForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RentalManagementForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RentalManagementForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddRental;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnReservations;
    private javax.swing.JButton btnReturnMovie;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableRentals;
    // End of variables declaration//GEN-END:variables
}
