/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.LocalDate;

import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


import javax.swing.JOptionPane;
/**
 *
 * @author death
 */
public class ReservationListForm extends javax.swing.JFrame {

    private int customerId;
    private RentalManagementForm parent;
    
    /**
     * Creates new form ReservationManagementForm
     */
    public ReservationListForm(int customerId, RentalManagementForm parent) {
        
        setTitle("Mana Movie Rental System");
        
        initComponents();
        
        this.customerId = customerId;
        this.parent = parent;
        
        loadReservations();
        
    }
    
    
    public void loadReservations() {
        
        try (Connection conn = DBConnection.connect()){
            
            String sql = "SELECT Reservations.id AS reservation_id, Reservations.movie_id, Movies.title, Reservations.format, Reservations.reservation_date " + 
                         "FROM Reservations " + 
                         "JOIN Movies ON Reservations.movie_id = Movies.id " + 
                         "WHERE Reservations.user_id = ?"; 
            
            PreparedStatement stmt = conn.prepareStatement(sql); 
            stmt.setInt(1, customerId);
            ResultSet rs = stmt.executeQuery(); 
            
            DefaultTableModel model = new DefaultTableModel (
                new String [] {"Reservation ID", "Movie ID",  "Movie Title", "Format", "Reservation Date"}, 0 
            );
            
            while (rs.next()) {
                
                model.addRow(new Object[] {
                    rs.getInt("reservation_id"), 
                    rs.getInt("movie_id"),
                    rs.getString("title"), 
                    rs.getString("format"), 
                    rs.getString("reservation_date")
                });
                
            }
            
            tableReservations.setModel(model);
            
            
        } catch (Exception e) { 
            
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error loading reservations.");
            
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableReservations = new javax.swing.JTable();
        btnConvertToRental = new javax.swing.JButton();
        btnCancelReservation = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Reservations List");

        tableReservations.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableReservations);

        btnConvertToRental.setText("Convert to Rental");
        btnConvertToRental.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertToRentalActionPerformed(evt);
            }
        });

        btnCancelReservation.setText("Cancel Reservation");
        btnCancelReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelReservationActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnConvertToRental)
                                .addGap(29, 29, 29)
                                .addComponent(btnCancelReservation)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCancel))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 786, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(371, 371, 371))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConvertToRental)
                    .addComponent(btnCancelReservation)
                    .addComponent(btnCancel))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
        
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnConvertToRentalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertToRentalActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = tableReservations.getSelectedRow(); 
        
        if (selectedRow == -1) {
            
            JOptionPane.showMessageDialog(this, "Please select a reservation first.");
            return;
        }
        
        int reservationId = (int) tableReservations.getValueAt(selectedRow, 0); 
        int movieId = (int) tableReservations.getValueAt(selectedRow, 1); 
        String format = (String) tableReservations.getValueAt(selectedRow, 3); 
        
        AddRentalDetailsForm rentalForm = new AddRentalDetailsForm (movieId, customerId, format, reservationId, parent, this); 
        rentalForm.setVisible(true); 
        // this.dispose();
        
    }//GEN-LAST:event_btnConvertToRentalActionPerformed

    private void btnCancelReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelReservationActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = tableReservations.getSelectedRow(); 
        
        if (selectedRow == -1) {
            
            JOptionPane.showMessageDialog(this, "Please select a reservation to cancel.");
            return;
            
        }
        
        int reservationId = (int) tableReservations.getValueAt(selectedRow, 0); 
        
        int confirm = JOptionPane.showConfirmDialog( 
                this,
                "Confim reservation cancellation:", 
                "Confirm Cancellation", 
                JOptionPane.YES_NO_OPTION
        );
        
        if (confirm != JOptionPane.YES_OPTION){
            
            return;
            
        }
        
        try (Connection conn = DBConnection.connect()) {
            
            String sql = "DELETE FROM Reservations WHERE id = ?"; 
            PreparedStatement stmt = conn.prepareStatement(sql); 
            stmt.setInt(1, reservationId);
            stmt.executeUpdate(); 
            
            JOptionPane.showMessageDialog(this, "Reservation canceled."); 
            loadReservations();
            
            
        } catch (Exception e) { 
            
            e.printStackTrace(); 
            JOptionPane.showMessageDialog(this, "Unable to cancel reservation.");
            
        }
        
        
        
    }//GEN-LAST:event_btnCancelReservationActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ReservationListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ReservationListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ReservationListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ReservationListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ReservationListForm().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCancelReservation;
    private javax.swing.JButton btnConvertToRental;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableReservations;
    // End of variables declaration//GEN-END:variables
}
