
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.LocalDate;

import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author death
 */
public class ReturnRentalDetailsForm extends javax.swing.JFrame {

    private int movieId;
    private int customerId; 
    private RentalManagementForm parent;
    
    /**
     * Creates new form AddRentalDetailsForm
     */
    public ReturnRentalDetailsForm(int movieId, int customerId, RentalManagementForm parent) {
        
        initComponents();
        
        this.movieId = movieId;
        this.customerId = customerId;
        this.parent = parent;
        
        loadRentalDetails(); 
        
    }
    
    private void loadRentalDetails() {
        
        try (Connection conn = DBConnection.connect()){
            
            String sql = "SELECT Rentals.*, Movies.title, Movies.price_per_day, Users.first_name, Users.last_name " + 
                         "FROM Rentals " + 
                         "JOIN Movies ON Rentals.movie_id = Movies.id " +
                         "JOIN Users ON Rentals.customer_id = Users.id " +
                         "WHERE Rentals.movie_id = ? AND Rentals.customer_id = ?"; 
            
            PreparedStatement stmt = conn.prepareStatement(sql); 
            stmt.setInt(1, movieId);
            stmt.setInt(2, customerId);
            
            ResultSet rs = stmt.executeQuery(); 
            
            if (rs.next()) {
                
                txtMovieTitle.setText(rs.getString("title"));
                txtMovieFormat.setText(rs.getString("format"));
                txtCustomerName.setText(rs.getString("first_name") + " " + rs.getString("last_name"));
                txtRentDate.setText(rs.getString("rent_date"));
                txtReturnDate.setText(rs.getString("return_date")); 
                txtPricePerDay.setText(rs.getString("price_per_day"));
                
                java.sql.Date rentDate = rs.getDate("rent_date"); 
                java.sql.Date returnDate = rs.getDate("return_date"); 
                long diffInMillis = returnDate.getTime() - rentDate.getTime(); 
                long days = (diffInMillis / ( 1000 * 60 * 60 * 24)) + 1; 
                txtDaysRented.setText(String.valueOf(days)); 
                
                double pricePerDay = rs.getDouble("price_per_day"); 
                double totalCost = days * pricePerDay; 
                txtTotalCost.setText(String.format("%.2f", totalCost)); 
                
            } else { 
                
                JOptionPane.showMessageDialog(this, "Unable to locate rental.");
                this.dispose();
                
            }
            
        } catch (Exception e) {
            
            e.printStackTrace(); 
            JOptionPane.showMessageDialog(this, "Unable to load rental details.");
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnConfirmReturn = new javax.swing.JButton();
        btnCancelReturn = new javax.swing.JButton();
        txtMovieTitle = new javax.swing.JTextField();
        txtMovieFormat = new javax.swing.JTextField();
        txtCustomerName = new javax.swing.JTextField();
        txtRentDate = new javax.swing.JTextField();
        txtReturnDate = new javax.swing.JTextField();
        txtPricePerDay = new javax.swing.JTextField();
        txtDaysRented = new javax.swing.JTextField();
        txtTotalCost = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Confirm Return Details");

        jLabel2.setText("Movie Title:");

        jLabel3.setText("Format:");

        jLabel4.setText("Customer Name:");

        jLabel5.setText("Rent Date:");

        jLabel6.setText("Return Date:");

        jLabel7.setText("Price Per Day:");

        jLabel8.setText("Days Rented:");

        jLabel9.setText("Total Cost:");

        btnConfirmReturn.setText("Confirm Return");
        btnConfirmReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmReturnActionPerformed(evt);
            }
        });

        btnCancelReturn.setText("Cancel Return");
        btnCancelReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelReturnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnConfirmReturn)
                        .addGap(45, 45, 45)
                        .addComponent(btnCancelReturn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9))
                                .addGap(2, 2, 2))
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtMovieTitle)
                                .addComponent(txtMovieFormat)
                                .addComponent(txtCustomerName)
                                .addComponent(txtRentDate)
                                .addComponent(txtReturnDate)
                                .addComponent(txtPricePerDay)
                                .addComponent(txtDaysRented)
                                .addComponent(txtTotalCost, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)))))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMovieTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMovieFormat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtRentDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtReturnDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtPricePerDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtDaysRented, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtTotalCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmReturn)
                    .addComponent(btnCancelReturn))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelReturnActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
        
    }//GEN-LAST:event_btnCancelReturnActionPerformed

    private void btnConfirmReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmReturnActionPerformed
        // TODO add your handling code here:
        
        try (Connection conn = DBConnection.connect()) {
            
            String updateRentalSql = "UPDATE Rentals SET return_date = ?, status = 'Returned' WHERE movie_id = ? AND customer_id = ?"; 
            PreparedStatement rentalStmt = conn.prepareStatement(updateRentalSql); 
            rentalStmt.setDate(1, new java.sql.Date(System.currentTimeMillis())); 
            rentalStmt.setInt(2, movieId);
            rentalStmt.setInt(3, customerId);
            rentalStmt.executeUpdate(); 
            
            String format = txtMovieFormat.getText(); 
            
            String updateUnitsSql; 
            
            if (format.equalsIgnoreCase("DVD")){ 
                
                updateUnitsSql = "UPDATE Movies SET dvd_units = dvd_units + 1 WHERE id = ?"; 
                
            } else {
                
                updateUnitsSql = "UPDATE Movies SET blu_ray_units = blu_ray_units + 1 WHERE id = ?"; 
                
            }
            
            PreparedStatement unitStmt = conn.prepareStatement(updateUnitsSql); 
            unitStmt.setInt(1, movieId); 
            unitStmt.executeUpdate(); 
            
            JOptionPane.showMessageDialog(this, "Rental successully returned.");
            
            if (parent != null) { 
                
                parent.loadRentals();
                
            }
            
            this.dispose();
            
        } catch (Exception e) {
            
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Unable to process return.");
            
        } 
        
    }//GEN-LAST:event_btnConfirmReturnActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AddRentalDetailsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AddRentalDetailsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AddRentalDetailsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AddRentalDetailsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AddRentalDetailsForm().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelReturn;
    private javax.swing.JButton btnConfirmReturn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCustomerName;
    private javax.swing.JTextField txtDaysRented;
    private javax.swing.JTextField txtMovieFormat;
    private javax.swing.JTextField txtMovieTitle;
    private javax.swing.JTextField txtPricePerDay;
    private javax.swing.JTextField txtRentDate;
    private javax.swing.JTextField txtReturnDate;
    private javax.swing.JTextField txtTotalCost;
    // End of variables declaration//GEN-END:variables
}
